// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZY0wNNRLma0J80buwyXw_giNDsWgkt0w',
    appId: '1:295457492318:web:b696dfea3fa2a38a6393cf',
    messagingSenderId: '295457492318',
    projectId: 'fullaccezz',
    authDomain: 'fullaccezz.firebaseapp.com',
    storageBucket: 'fullaccezz.appspot.com',
    measurementId: 'G-86TLKL2THV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ZRx1BO_UWy3vgpf0zbes9AP30LoGRIQ',
    appId: '1:295457492318:android:00d3556b38c174cb6393cf',
    messagingSenderId: '295457492318',
    projectId: 'fullaccezz',
    storageBucket: 'fullaccezz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOhTYCub-uU3FuRhK_hzax88uhNVliKHs',
    appId: '1:295457492318:ios:5d378953bae6aa2d6393cf',
    messagingSenderId: '295457492318',
    projectId: 'fullaccezz',
    storageBucket: 'fullaccezz.appspot.com',
    iosClientId: '295457492318-apavfm1nqhcuoc5rdudus5qggc40nh1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynuu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOhTYCub-uU3FuRhK_hzax88uhNVliKHs',
    appId: '1:295457492318:ios:5d378953bae6aa2d6393cf',
    messagingSenderId: '295457492318',
    projectId: 'fullaccezz',
    storageBucket: 'fullaccezz.appspot.com',
    iosClientId: '295457492318-apavfm1nqhcuoc5rdudus5qggc40nh1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynuu',
  );
}
